### PR TITLE
Add enum for type, subtype and aclass and add serialize trait

### PR DESCRIPTION
**Pull request by Ebolon**
I added three enums for `type`, `subtype` and `aclass`. The Kraken doc is not on par with the real api. But it should be easy to adjust. 
Additionally I added the `Serialize` trait. I like to cache the results without the need to map the values to new objects. Sadly it is not that easy to add the serialization feature from outside. I hope you are agreeing that it make sense to have this in this library.

### CODE REVIEW

**Comment by gmosx** [comment]
Hmm, it looks good. I may introduce a 'serialize' feature to the crate.

**Comment by Ebolon** [comment]
I added the possibility to serialize / deserialize the f64 strings as well to an f64 type. I hope this suites for your too.

**Comment by gmosx** [comment]
Tbh, I don't really like the f64 conversion stuff. Maybe the user would like to deserialize into e.g. rust_decimal::Decimal.
Can you please revert the latest commit (and for example open a separate PR?)
I would like to merge the enum stuff and consider f64, etc separately.

**Comment by Ebolon** [comment]
Yes of course. I have reverted it.

**Comment by gmosx** [comment]
Thanks for reverting. I have one more question. What will happen if Kraken adds a new e.g. `LedgerType` that is not part of the enum. How will serde handle this case?

**Comment by Ebolon** [comment]
This would result in a runtime error.

**Comment by gmosx** [comment]
Are you sure you would like a runtime error (panic?) if the API returned a new string for e.g. `ledgerType`? Let's say I had an app that was displaying ledgers, having the `ledgerType` as a string  would be more robust. The app could display the ledger it expects (or even the 'novel' ledger).

I think using the `#[serde(other)]` approach is the way to go.

**Comment by Ebolon** [comment]
After giving it a second thought. I will have a look if I implement the enums as trait for the response. I think a enum with and unknown state is bad practice, because you would loose information in case of serializing and deserializing it.

**Comment by Ebolon** [comment]
My goal would be that the library providing enums so I do not handle with the strings (ledger types...) myself. How do you feel about the trait idea for optional enum typing? Maybe for other types as well.

**Comment by gmosx** [comment]
Hm, that's an interesting idea,thank you for refining this MR. 

One alternative idea, what about if the 'Unknown' variant of the enum was a tuple struct with a string attribute of the 'unknown' value? That way no information would be lost? Thoughts?

**Comment by gmosx** [comment]
I will merge with minor edits.

**Comment by gmosx** [comment]
In a follow-up MR, I removed the trait. AFAICS it only adds noise, for no clear benefit. (Correct me if I am wrong).

**Pull request merged**
